# Generated by Django 4.2.2 on 2023-07-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_tusks_tusks_id_remove_user_tusks_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('news_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
