# Generated by Django 4.2.2 on 2023-06-25 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tusks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название задачи')),
                ('tusk_description', models.TextField(max_length=1500, verbose_name='Описание задачи')),
                ('date', models.DateTimeField(verbose_name='дедлайн')),
            ],
            options={
                'verbose_name': ('Task',),
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='User_Tusks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tusks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tusks.tusks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('User_Task',),
                'verbose_name_plural': 'User_Tasks',
            },
        ),
    ]
