# Generated by Django 4.2.2 on 2023-06-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tusks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_commentary', models.TextField(max_length=500, verbose_name='Комментарий к задаче')),
                ('tusks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tusks.tusks')),
            ],
        ),
    ]
