# Generated by Django 4.2.2 on 2023-06-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tusks', '0002_task_commentary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField(max_length=500, verbose_name='Комментарий к задаче')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('tusks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tusks.tusks')),
            ],
            options={
                'verbose_name': ('Task_Commentary',),
                'verbose_name_plural': 'Task_Commentaries',
            },
        ),
        migrations.DeleteModel(
            name='Task_Commentary',
        ),
    ]
