# Generated by Django 4.2.2 on 2023-06-28 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tusks', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tusks.post'),
        ),
    ]
