# Generated by Django 4.2.2 on 2023-06-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusks', '0005_task_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
