# Generated by Django 4.2.2 on 2023-06-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tusks', '0006_remove_task_comment_post_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_comment',
            name='tusks_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tusks.tusks'),
        ),
    ]
