# Generated by Django 4.2.2 on 2023-06-28 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tusks', '0007_alter_task_comment_tusks_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_comment',
            options={'verbose_name': ('Task Commentary',), 'verbose_name_plural': 'Task Commentaries'},
        ),
        migrations.AlterModelOptions(
            name='user_tusks',
            options={'verbose_name': ('User Task',), 'verbose_name_plural': 'User Tasks'},
        ),
        migrations.AlterField(
            model_name='user_tusks',
            name='tusks_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tusks_id', to='tusks.tusks'),
        ),
        migrations.AlterField(
            model_name='user_tusks',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
