# Generated by Django 4.2.2 on 2023-06-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusks', '0010_alter_task_comment_options_alter_tusks_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complited',
        ),
    ]
