# Generated by Django 4.2.2 on 2023-07-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusks', '0011_delete_complited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tusks',
            name='tags',
            field=models.ManyToManyField(to='tusks.tag'),
        ),
    ]
